swagger: '2.0'
info:
  title: Example API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /balance:
    get:
      operationId: app.get_balance
      summary: Get balance
      parameters:
        - name: API_KEY
          in: query
          type: string
          pattern: "^[a-zA-Z0-9]*$"
      responses:
        200:
          description: Return balance
          schema:
            type: array
            items:
              $ref: '#/definitions/Balance
         404:
              description: API key does not exist
 

parameters:
  pet_id:
    name: pet_id
    description: Pet's Unique identifier
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"

definitions:
  Balance:
    type: object
    required:
      - API_KEY
      - animal_type
    properties:
      API_KEY:
        type: string
        description: Unique identifier
        example: "123"
        readOnly: true
      balance:
        type: number
        description: Balance
        example: 100.0
        minLength: 0.0
